### ISSUE TITLE
Gem farm

### ISSUE THREAD

**Issue by berkayceylan00** [shamiulalamupom/rokfarmbot#1]

**Comment by berkayceylan00** [comment]
did you completed the gem collecting bot?

**Comment by berkayceylan00** [comment]
did you completed the gem collecting bot and how i can install

**Comment by shamiulalamupom** [comment]
No, I haven't created that. I stopped playing the game, and that's why I stopped working on it as well. But there is a simple code to farm one node of gem after a while, you can alter the code by forking it to make a better version. I haven't implemented the gem node searching algorithm, a hint for you would be the matrix. Happy gaming!!!

**Comment by shamiulalamupom** [comment]
Now, you can follow README.md to follow the instructions and don't forget to star the project and follow me 😄
